[project]
name = "pretix-trainings"
dynamic = ["version"]
description = "Raumverwaltung, mehrtaegige Kurse und Teilnahmebescheinigungen fuer pretix-Trainings"
readme = "README.rst"
license = {text = "Apache"}
keywords = ["pretix"]
authors = [
    {name = "Tobias Berndt", email = "claude.tobi@die-wg.vodka"},
]
maintainers = [
    {name = "Tobias Berndt", email = "claude.tobi@die-wg.vodka"},
]

dependencies = [
    "vobject",
]

[project.entry-points."pretix.plugin"]
pretix_trainings = "pretix_trainings:PretixPluginMeta"

[project.entry-points."distutils.commands"]
build = "pretix_plugin_build.build:CustomBuild"

[build-system]
requires = [
    "setuptools",
    "pretix-plugin-build",
]

[project.urls]
homepage = "https://github.com/example-org/pretix-trainings"
repository = "https://github.com/example-org/pretix-trainings"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "pretix_trainings.__version__"}

[tool.setuptools.packages.find]
include = ["pretix*"]
namespaces = false
