# Generated by Django 5.2.17 on 2026-08-13 23:45

import django.db.models.deletion
import pretix.base.models.base
from django.conf import settings
from django.db import migrations, models

import pretix_trainings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0306_alter_eventmetaproperty_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(max_length=190, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_certificate",
                        to="pretixbase.orderposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificateApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_certificate_approval",
                        to="pretixbase.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificateLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=190)),
                (
                    "layout",
                    models.TextField(
                        default='[{"type":"textarea","left":"20","bottom":"260","fontsize":"22","color":[0,0,0,1],"fontfamily":"Open Sans","bold":true,"italic":false,"width":"170","content":"other","text":"Teilnahmebescheinigung","text_i18n":{},"align":"center"},{"type":"textarea","left":"20","bottom":"220","fontsize":"14","color":[0,0,0,1],"fontfamily":"Open Sans","bold":false,"italic":false,"width":"170","content":"attendee_name","text":"Max Mustermann","align":"center"},{"type":"textarea","left":"20","bottom":"200","fontsize":"12","color":[0,0,0,1],"fontfamily":"Open Sans","bold":false,"italic":false,"width":"170","content":"course_title","text":"Musterschulung","align":"center"},{"type":"textarea","left":"20","bottom":"180","fontsize":"10","color":[0,0,0,1],"fontfamily":"Open Sans","bold":false,"italic":false,"width":"170","content":"course_dates","text":"Di, 15.09.2026, 09:00\\u201317:00 Uhr","align":"center","downward":true},{"type":"textarea","left":"20","bottom":"150","fontsize":"10","color":[0,0,0,1],"fontfamily":"Open Sans","bold":false,"italic":false,"width":"170","content":"course_hours","text":"8,0","align":"center"},{"type":"textarea","left":"20","bottom":"40","fontsize":"9","color":[0,0,0,1],"fontfamily":"Open Sans","bold":false,"italic":false,"width":"80","content":"issue_date","text":"01.01.2026","align":"left"},{"type":"textarea","left":"110","bottom":"40","fontsize":"9","color":[0,0,0,1],"fontfamily":"Open Sans","bold":false,"italic":false,"width":"80","content":"certificate_number","text":"2026-0001","align":"right"}]'
                    ),
                ),
                (
                    "background",
                    models.FileField(
                        max_length=255,
                        null=True,
                        upload_to=pretix_trainings.models._certificate_background_name,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_certificate_layouts",
                        to="pretixbase.event",
                    ),
                ),
                ("item_filter", models.ManyToManyField(to="pretixbase.item")),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("room", models.CharField(max_length=255)),
                (
                    "checkin_list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pretixbase.checkinlist",
                    ),
                ),
                (
                    "subevent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_sessions",
                        to="pretixbase.subevent",
                    ),
                ),
            ],
            options={
                "ordering": ("subevent", "sequence"),
                "unique_together": {("subevent", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="RoomChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("old_value", models.CharField(max_length=255)),
                ("new_value", models.CharField(max_length=255)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("recipient_count", models.IntegerField(null=True)),
                ("discarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subevent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_room_changes",
                        to="pretixbase.subevent",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_changes",
                        to="pretix_trainings.session",
                    ),
                ),
            ],
            options={
                "ordering": ("-detected_at",),
                "indexes": [
                    models.Index(
                        fields=["subevent", "sent_at"],
                        name="pretix_trai_subeven_11eff9_idx",
                    )
                ],
            },
        ),
    ]
